### PR TITLE
Laravel 10.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 9.x.

**Before merging**, you need to:

- Checkout the `l10-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/laravel-discord-logger.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "marvinlabs/laravel-discord-logger": "dev-l10-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by fh32000** [comment]
@laravel-shift good job

**Comment by svpernova09** [comment]
@laravel-shift good bot. Cheers!

**Comment by sgtcoder** [comment]
To fix the issue with:

```
Declaration of MarvinLabs\DiscordLogger\LogHandler::write(array $record): void must be compatible with Monolog\Handler\AbstractProcessingHandler::write(Monolog\LogRecord $record): void
```

I updated this file: MarvinLabs\DiscordLogger\LogHandler with the following

```
use Monolog\LogRecord;

public function write(LogRecord $record): void
    {
        $record = $record->toArray();

        foreach ($this->recordToMessage->buildMessages($record) as $message) {
            $this->discord->send($message);
        }
    }
    ```

**Comment by Bmohsen** [comment]
> To fix the issue with:
> 
> ```
> Declaration of MarvinLabs\DiscordLogger\LogHandler::write(array $record): void must be compatible with Monolog\Handler\AbstractProcessingHandler::write(Monolog\LogRecord $record): void
> ```
> 
> I updated this file: MarvinLabs\DiscordLogger\LogHandler with the following
> 
> ```
> use Monolog\LogRecord;
> 
> public function write(LogRecord $record): void
>     {
>         $record = $record->toArray();
> 
>         foreach ($this->recordToMessage->buildMessages($record) as $message) {
>             $this->discord->send($message);
>         }
>     }
>     ```
> ```

thank you, just saved my day.

**Pull request merged**
